GUIDES = {
    "train-an-ai-agent": {
        "path": "/train-an-ai-agent/",
        "title": "How to train an AI agent with your own knowledge",
        "eyebrow": "Practical agent training",
        "lead": "Turn documents, examples, corrections and decisions into files an agent can inspect, cite and carry into its next project.",
        "meta": "A practical guide to training one AI agent with documents, examples, corrections, versioned files and human approval.",
        "sections": [
            ("Start with one agent, not a fleet", "Give the learner a clear training mode before assigning a job. Add real knowledge in small, inspectable files instead of hiding everything inside one enormous prompt."),
            ("Process before you trust", "Let the agent inspect the new material as a set. Conflicts, missing authority and unclear exceptions should become questions rather than invented answers."),
            ("Approve durable memory", "Teacher explanations become visible memory and proposed rules. Only reviewed files become active; generated work remains a draft until a human approves it."),
        ],
        "takeaway": "Good agent training is a reviewable file history—not a forgotten chat.",
        "related": [("Agent memory", "/agent-memory/"), ("AGENTS.md", "/agents-md/"), ("See fictional histories", "/demos/")],
    },
    "agent-memory": {
        "path": "/agent-memory/",
        "title": "Agent memory should be visible",
        "eyebrow": "Cognitive memory",
        "lead": "Useful memory is something an owner can read, correct, version and remove—not an invisible promise that a chat will remember.",
        "meta": "Understand visible cognitive memory for AI agents: teacher notes, approved files, corrections, provenance and portable history.",
        "sections": [
            ("Memory needs provenance", "Every remembered rule should show where it came from: a document, an example, a correction or an explicit teacher answer."),
            ("Corrections belong beside knowledge", "A correction is not merely another message. Store it as a durable rule with a revision and an approval state so later behavior can be traced."),
            ("Portable beats trapped", "The owner should be able to download ordinary files and continue in another Codex project or self-hosted environment."),
        ],
        "takeaway": "If the owner cannot inspect it, it is not trustworthy long-term memory.",
        "related": [("Train an agent", "/train-an-ai-agent/"), ("YAML rules", "/yaml-rules-for-ai-agents/"), ("Version control", "/version-control-for-ai-agents/")],
    },
    "agents-md": {
        "path": "/agents-md/",
        "title": "What belongs in AGENTS.md?",
        "eyebrow": "Portable instructions",
        "lead": "AGENTS.md is the root instruction map: current mode, learning rules, authority boundaries and where the agent should find its approved memory.",
        "meta": "Learn how AGENTS.md can define training mode, knowledge use, uncertainty, approval boundaries and portable agent behavior.",
        "sections": [
            ("Describe the current mode", "A newly created agent begins in training mode with no concrete task. That keeps learning separate from unsupported autonomous work."),
            ("Point to authoritative files", "The root file should tell the agent to read approved rules, knowledge, examples, procedures, corrections, tests and teacher notes."),
            ("State action boundaries", "Publishing, sending, purchasing and changing external systems remain human-controlled even when an output is approved."),
        ],
        "takeaway": "AGENTS.md is a map and contract, not a dumping ground for every document.",
        "related": [("Agent memory", "/agent-memory/"), ("YAML rules", "/yaml-rules-for-ai-agents/"), ("Self-host", "/self-host/")],
    },
    "yaml-rules-for-ai-agents": {
        "path": "/yaml-rules-for-ai-agents/",
        "title": "YAML rules for AI agents",
        "eyebrow": "Structured behavior",
        "lead": "Use YAML when a rule needs explicit fields, limits and tests. Keep explanation in readable notes and authority in structured policy.",
        "meta": "A practical guide to YAML rules for AI agents, including approval boundaries, uncertainty, tests and versioned corrections.",
        "sections": [
            ("Make the boundary testable", "A structured rule can say which files are active, when the agent must ask and which external actions always require a human."),
            ("Keep proposed rules reviewable", "An agent may suggest a rule after a clarification, but the suggestion stays proposed until the teacher approves it."),
            ("Prefer narrow rules", "One precise correction is easier to test and retire than a large policy that mixes unrelated decisions."),
        ],
        "takeaway": "YAML is useful when structure clarifies authority; it should not replace human-readable context.",
        "related": [("AGENTS.md", "/agents-md/"), ("Version control", "/version-control-for-ai-agents/"), ("Security manifests", "/ai-agent-security/")],
    },
    "version-control-for-ai-agents": {
        "path": "/version-control-for-ai-agents/",
        "title": "Version control for agent behavior",
        "eyebrow": "Git-shaped learning",
        "lead": "Treat changes in agent knowledge like code changes: show the diff, preserve the earlier version and require a reviewable decision.",
        "meta": "Use version control concepts for AI-agent knowledge, corrections, tests, approvals and rollback.",
        "sections": [
            ("Every change has a state", "Proposed, active and retired are different facts. The interface should never call a proposed lesson learned before approval."),
            ("History supports correction", "When a rule changes, retain the earlier checksum, revision and reason. Owners can then understand why an answer changed."),
            ("Rollback is part of trust", "Portable files and explicit versions let the owner return to a known state without deleting unrelated learning."),
        ],
        "takeaway": "An agent becomes easier to trust when behavior changes are as inspectable as source changes.",
        "related": [("Agent memory", "/agent-memory/"), ("YAML rules", "/yaml-rules-for-ai-agents/"), ("Open source", "/open-source/")],
    },
    "ai-agent-security": {
        "path": "/ai-agent-security/",
        "title": "AI-agent security starts with less access",
        "eyebrow": "Least privilege",
        "lead": "The model may request exact facts and explain why. A separate policy—not the model—must decide what the task receives.",
        "meta": "Explore least-privilege AI-agent security, data-access manifests, prompt-injection tests and transparent privacy receipts.",
        "sections": [
            ("Separate request from authority", "A persuasive model response is still input. It cannot change field policy, read limits, expiry, destination or memory treatment."),
            ("Use temporary context capsules", "Release only approved fields for one task and discard the temporary context after the result."),
            ("Show the receipt", "Record requested, released and withheld fields so an owner can compare the result with the actual access path."),
        ],
        "takeaway": "Give the agent the task—not the whole file.",
        "related": [("Open the Security Lab", "SECURITY_LAB"), ("Privacy and rules", "/principles/"), ("Transparency", "/transparency/")],
    },
    "transparency": {
        "path": "/transparency/",
        "title": "How Teach the Company actually works",
        "eyebrow": "Transparency",
        "lead": "The classroom creates portable context files. It does not claim to change model weights, publish autonomously or make private learning public.",
        "meta": "Teach the Company architecture, privacy boundaries, current limitations, model use and evidence.",
        "sections": [
            ("One private classroom", "Hosted access is invitation-only. Uploaded files have no public media route, and browser ownership is checked on every private view and download."),
            ("One internal model", "The hosted classroom can use an internal local model with bounded context. Evidence mode remains an honest fallback when a provider is unavailable."),
            ("Explicit unfinished work", "Automatic public email is off. The future security lab uses synthetic records only. Claims appear publicly only after matching tests exist."),
        ],
        "takeaway": "Transparency means showing limitations and states, not only architecture diagrams.",
        "related": [("Privacy and rules", "/principles/"), ("Changelog", "/changelog/"), ("Open source", "/open-source/")],
    },
    "open-source": {
        "path": "/open-source/",
        "title": "A portable, self-hosted agent classroom",
        "eyebrow": "Apache-2.0 open source",
        "lead": "The complete Docker framework is public so people and companies can run agent training on infrastructure they control.",
        "meta": "The complete open-source Teach the Company Docker framework: Django, agent files, model adapters, tests and self-hosting.",
        "sections": [
            ("The files are the portable product", "AGENTS.md, YAML rules, memory, knowledge, examples, corrections and tests can leave the website as an ordinary ZIP."),
            ("Docker is the classroom shell", "The container runs ingestion, review and history. It is not the agent identity and it does not trap the learned files."),
            ("Complete source, clean data boundary", "The public repository includes application code, Docker, migrations, tests, model adapters and the synthetic security lab. Credentials, private classrooms and backups remain private runtime state."),
        ],
        "takeaway": "Clone the Apache-2.0 repository for self-hosting, or request an invitation when you want the managed service.",
        "related": [("Self-host", "/self-host/"), ("AGENTS.md", "/agents-md/"), ("Transparency", "/transparency/")],
    },
    "changelog": {
        "path": "/changelog/",
        "title": "Teach the Company changelog",
        "eyebrow": "Visible progress",
        "lead": "A curated record of user-visible capability—not a dump of private deployment details or internal commits.",
        "meta": "A transparent Teach the Company changelog covering the private classroom, portable files, local model and security lab.",
        "sections": [
            ("One-agent classroom", "The product was simplified around one person teaching one private agent, with visible files, explicit processing and human approval."),
            ("Portable Codex framework", "New classrooms create AGENTS.md, structured YAML rules and cognitive memory, with browser viewing and a downloadable ZIP."),
            ("Agent Security Lab", "The synthetic Only What It Needs experiment adds deterministic least-privilege decisions and privacy receipts without accepting real records."),
        ],
        "takeaway": "Release dates and evidence links will be added when each public release is accepted.",
        "related": [("Transparency", "/transparency/"), ("Open source", "/open-source/"), ("Demo histories", "/demos/")],
    },
}
