from django.urls import path
from django.views.generic import RedirectView

from . import views


app_name = "academy"

urlpatterns = [
    path("favicon.ico", views.favicon, {"filename": "favicon.ico"}, name="favicon_ico"),
    path("favicon.svg", views.favicon, {"filename": "favicon.svg"}, name="favicon_svg"),
    path("apple-touch-icon.png", views.mobile_icon, {"filename": "apple-touch-icon.png"}, name="apple_touch_icon"),
    path("apple-touch-icon-precomposed.png", views.mobile_icon, {"filename": "apple-touch-icon.png"}, name="apple_touch_icon_precomposed"),
    path("site.webmanifest", views.site_manifest, name="site_manifest"),
    path("manifest.webmanifest", views.site_manifest, name="manifest_webmanifest"),
    path("", views.home, name="home"),
    path("demos/", views.demos, name="demos"),
    path("curriculum/", views.curriculum, name="curriculum"),
    path("school/", views.school, name="school"),
    path("school/index.<str:format>", views.school_index, name="school_index"),
    path("school/<slug:slug>/", views.lesson, name="lesson"),
    path("school/<slug:slug>.<str:format>", views.lesson, name="lesson_format"),
    path("manuals/", views.manuals, name="manuals"),
    path("manuals/index.<str:format>", views.manual_index, name="manual_index"),
    path("manuals/<slug:slug>/", views.manual, name="manual"),
    path("manuals/<slug:slug>.<str:format>", views.manual, name="manual_format"),
    path("projects/", views.projects, name="projects"),
    path("projects/index.<str:format>", views.project_index, name="project_index"),
    path("projects/<slug:slug>/prompt.txt", views.project_prompt, name="project_prompt"),
    path("projects/<slug:slug>/", views.project, name="project"),
    path("projects/<slug:slug>.<str:format>", views.project, name="project_format"),
    path("compose/", views.compose_school, name="compose"),
    path("compose/download/", views.composition_download, name="composition_download"),
    path("suggest/", views.suggest, name="suggest"),
    path("suggest/thanks/", views.suggest_thanks, name="suggest_thanks"),
    path("knowledge/freshness/", views.freshness, name="freshness"),
    path("self-host/", views.self_host, name="self_host"),
    path("request-access/", views.request_access, name="request_access"),
    path("start/", views.start, name="start"),
    path("join/<str:token>/", views.join, name="join"),
    path("handoff/<str:token>/", views.accept_handoff, name="accept_handoff"),
    path("studio/<uuid:public_id>/", views.studio, name="studio"),
    path("studio/<uuid:public_id>/move-to-agent/", views.create_handoff, name="create_handoff"),
    path("studio/<uuid:public_id>/teach/", views.teach_agent, name="teach_agent"),
    path("studio/<uuid:public_id>/process/", views.process_training, name="process_training"),
    path("studio/<uuid:public_id>/question/<uuid:question_id>/answer/", views.answer_training, name="answer_training"),
    path("studio/<uuid:public_id>/ask/", views.ask_agent, name="ask_agent"),
    path("studio/<uuid:public_id>/source/<uuid:source_id>/action/", views.source_action, name="source_action"),
    path("studio/<uuid:public_id>/source/<uuid:source_id>/", views.source_view, name="source_view"),
    path("studio/<uuid:public_id>/source/<uuid:source_id>/download/", views.source_download, name="source_download"),
    path("studio/<uuid:public_id>/source/<uuid:source_id>/original/", views.source_original_download, name="source_original_download"),
    path("studio/<uuid:public_id>/artifact/<uuid:artifact_id>/action/", views.artifact_action, name="artifact_action"),
    path("studio/<uuid:public_id>/artifact/<uuid:artifact_id>/download/", views.artifact_download, name="artifact_download"),
    path("studio/<uuid:public_id>/export/", views.export_training, name="export_training"),
    path("studio/<uuid:public_id>/lesson/<slug:module_slug>/", views.module, name="module"),
    path("studio/<uuid:public_id>/preview/", views.preview, name="preview"),
    path("challenge/<slug:slug>/", views.challenge, name="challenge"),
    path("principles/", views.principles, name="principles"),
    path("train-an-ai-agent/", views.guide, {"slug": "train-an-ai-agent"}, name="train_agent"),
    path("agent-memory/", views.guide, {"slug": "agent-memory"}, name="agent_memory"),
    path("agents-md/", views.guide, {"slug": "agents-md"}, name="agents_md"),
    path("yaml-rules-for-ai-agents/", views.guide, {"slug": "yaml-rules-for-ai-agents"}, name="yaml_rules"),
    path("version-control-for-ai-agents/", views.guide, {"slug": "version-control-for-ai-agents"}, name="version_control"),
    path("self-hosted-agent-training/", RedirectView.as_view(pattern_name="academy:self_host", permanent=True), name="self_host_alias"),
    path("ai-agent-security/", views.guide, {"slug": "ai-agent-security"}, name="ai_agent_security"),
    path("transparency/", views.guide, {"slug": "transparency"}, name="transparency"),
    path("open-source/", views.guide, {"slug": "open-source"}, name="open_source"),
    path("changelog/", views.guide, {"slug": "changelog"}, name="changelog"),
    path("robots.txt", views.robots, name="robots"),
    path("sitemap.xml", views.sitemap, name="sitemap"),
    path("llms.txt", views.llms_txt, name="llms_txt"),
    path("healthz/", views.health, name="health"),
]
