# Generated by Django 5.2.6 on 2026-09-30 22:41

import academy.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_trainingproject_creator_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
                ('use_count', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('use_case', models.TextField(max_length=700)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('invited', 'Invited'), ('closed', 'Closed')], default='requested', max_length=20)),
                ('source_fingerprint', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('artifact_type', models.CharField(default='answer', max_length=60)),
                ('logical_path', models.CharField(max_length=240)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Needs approval'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('source_titles', models.JSONField(blank=True, default=list)),
                ('safe_to_share', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='academy.trainingproject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LearningSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('note', 'Note'), ('link', 'Link'), ('document', 'Document'), ('example', 'Example'), ('procedure', 'Procedure'), ('correction', 'Correction'), ('test', 'Test')], default='note', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('logical_path', models.CharField(max_length=240)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('content_text', models.TextField(blank=True)),
                ('uploaded_file', models.FileField(blank=True, upload_to=academy.models.private_source_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('active', 'Active'), ('retired', 'Retired')], default='proposed', max_length=20)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(blank=True, editable=False, max_length=64)),
                ('safe_to_share', models.BooleanField(default=False)),
                ('learned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='academy.trainingproject')),
            ],
            options={
                'ordering': ('learned_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('source', 'Source learned'), ('correction', 'Correction learned'), ('test', 'Test completed'), ('artifact', 'Artifact created'), ('approval', 'Human approval'), ('publication', 'Published')], max_length=20)),
                ('headline', models.CharField(max_length=180)),
                ('detail', models.TextField(blank=True, max_length=1200)),
                ('safe_to_share', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to='academy.trainingproject')),
                ('related_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='academy.agentartifact')),
                ('related_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='academy.learningsource')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SourceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('content_text', models.TextField(blank=True)),
                ('checksum', models.CharField(max_length=64)),
                ('change_note', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('active', 'Active'), ('retired', 'Retired')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='academy.learningsource')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddConstraint(
            model_name='learningsource',
            constraint=models.UniqueConstraint(fields=('project', 'logical_path'), name='unique_project_learning_path'),
        ),
        migrations.AddConstraint(
            model_name='sourcerevision',
            constraint=models.UniqueConstraint(fields=('source', 'number'), name='unique_source_revision'),
        ),
    ]
