# Generated by Django 5.2.6 on 2026-10-01 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_training_questions_codex_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Request receipt'), ('outcome', 'Manual-review outcome')], max_length=20)),
                ('outcome', models.CharField(blank=True, max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('recipient_fingerprint', models.CharField(db_index=True, editable=False, max_length=64)),
                ('source_fingerprint', models.CharField(db_index=True, editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactional_emails', to='academy.accessrequest')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('access_request', 'kind'), name='unique_transactional_email_kind')],
            },
        ),
    ]
