# Generated by Django 5.2.6 on 2026-10-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_transactionalemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='notification_eligible',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
