# Generated by Django 5.2.6 on 2026-10-03 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_project_access_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('missing_topic', 'Missing topic'), ('correction', 'Correction'), ('experience', 'Practical experience')], max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(max_length=2000)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_fingerprint', models.CharField(db_index=True, editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('in_review', 'In review'), ('accepted', 'Accepted for editorial work'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('moderator_note', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TrustedKnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('publisher', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('lesson_ids', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('review_interval_days', models.PositiveSmallIntegerField(default=30)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_content_hash', models.CharField(blank=True, max_length=64)),
                ('last_final_url', models.URLField(blank=True, max_length=1000)),
                ('last_status', models.CharField(choices=[('never', 'Not checked'), ('baseline', 'Baseline recorded'), ('ok', 'No change detected'), ('changed', 'Change needs review'), ('error', 'Check failed')], default='never', max_length=16)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('publisher', 'title'),
            },
        ),
        migrations.CreateModel(
            name='PublicInputEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('actor_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['action', 'actor_hash', 'created_at'], name='public_input_actor_time')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('observed_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('needs_review', 'Needs editorial review'), ('conflict', 'Conflicting evidence'), ('accepted', 'Accepted for source update'), ('rejected', 'Rejected'), ('published', 'Published in a reviewed release')], db_index=True, default='needs_review', max_length=20)),
                ('evidence_excerpt', models.TextField(blank=True, max_length=4000)),
                ('change_summary', models.TextField(blank=True, max_length=1000)),
                ('conflict_flags', models.JSONField(blank=True, default=list)),
                ('proposed_update', models.TextField(blank=True, max_length=6000)),
                ('publication_reference', models.CharField(blank=True, max_length=200)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='academy.trustedknowledgesource')),
            ],
            options={
                'ordering': ('-detected_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('source', 'observed_hash'), name='unique_source_observed_hash')],
            },
        ),
    ]
