# Generated by Django 5.2.6 on 2026-10-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_publicsuggestion_trustedknowledgesource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedknowledgesource',
            name='last_etag',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trustedknowledgesource',
            name='last_modified_header',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trustedknowledgesource',
            name='review_interval_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
